import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { SimpleLineChart } from '../components/SimpleLineChart'
import { deriveFcaStatus, isFcaOverdue, listFcas } from '../lib/fca'
import { indicatorMeta, metricStatus, money, pct, periodKey } from '../lib/dashboard'
import type { DashboardFilters } from '../types/dashboard'
import type { FcaWithActions } from '../types/fca'
import type { HubBootstrap } from '../types/hub'

export function DepositantesPage({hub,filters}:{hub:HubBootstrap;filters:DashboardFilters}){
 const incoming=useMemo(()=>{const cnpj=sessionStorage.getItem('bi-logistico-v2:depositante')||'';if(cnpj)sessionStorage.removeItem('bi-logistico-v2:depositante');return cnpj},[])
 const[search,setSearch]=useState(''),[selectedCnpj,setSelectedCnpj]=useState(incoming),[fcas,setFcas]=useState<FcaWithActions[]>([]),[fcaLoading,setFcaLoading]=useState(false)
 useEffect(()=>{setFcaLoading(true);void listFcas().then(setFcas).catch(()=>setFcas([])).finally(()=>setFcaLoading(false))},[])
 const selectedPeriodKey=periodKey(filters.periodo)
 const rows=useMemo(()=>hub.depositantes.filter(d=>(!filters.supervisorId||d.supervisorId===filters.supervisorId)&&(!filters.moduloId||d.moduloId===filters.moduloId)&&(!search||`${d.nome} ${d.cnpj} ${d.codAllStrategy??''}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR')),[hub.depositantes,filters.supervisorId,filters.moduloId,search])
 useEffect(()=>{if(selectedCnpj&&!rows.some(r=>r.cnpj===selectedCnpj))setSelectedCnpj('')},[filters.supervisorId,filters.moduloId])
 const selected=hub.depositantes.find(d=>d.cnpj===selectedCnpj)??null
 const supervisor=selected?hub.supervisors.find(s=>s.supervisorId===selected.supervisorId):null
 const opCurrent=selected?hub.facts.kpiOperacional.find(r=>r.cnpj===selected.cnpj&&(!selectedPeriodKey||periodKey(r.periodo)===selectedPeriodKey)):undefined
 const invCurrent=selected?hub.facts.kpiInventarioDepositante.find(r=>r.cnpj===selected.cnpj&&(!selectedPeriodKey||periodKey(r.periodo)===selectedPeriodKey)):undefined
 const metaProd=indicatorMeta(hub,'Lead Time Produção'),metaRec=indicatorMeta(hub,'Lead Time Recebimento'),metaInv=indicatorMeta(hub,'Inventário')
 const history=selected?hub.facts.kpiOperacional.filter(r=>r.cnpj===selected.cnpj&&(!selectedPeriodKey||periodKey(r.periodo)<=selectedPeriodKey)).sort((a,b)=>periodKey(a.periodo).localeCompare(periodKey(b.periodo))).slice(-18):[]
 const invHistory=selected?hub.facts.kpiInventarioDepositante.filter(r=>r.cnpj===selected.cnpj&&(!selectedPeriodKey||periodKey(r.periodo)<=selectedPeriodKey)).sort((a,b)=>periodKey(a.periodo).localeCompare(periodKey(b.periodo))).slice(-18):[]
 const invMap=new Map(invHistory.map(r=>[periodKey(r.periodo),r.totalPct]))
 const periodKeys=Array.from(new Set([...history.map(r=>periodKey(r.periodo)),...invHistory.map(r=>periodKey(r.periodo))])).sort()
 const labelByKey=new Map([...history,...invHistory].map(r=>[periodKey(r.periodo),r.periodo]))
 const historySeries=[{label:'Produção',tone:'red' as const,values:history.map(r=>({periodo:r.periodo,value:r.producaoPct}))},{label:'Recebimento',tone:'gray' as const,values:history.map(r=>({periodo:r.periodo,value:r.recebimentoPct}))},{label:'Inventário',tone:'blue' as const,values:periodKeys.map(key=>({periodo:labelByKey.get(key)??key,value:invMap.get(key)??null}))}]
 const finance=selected?hub.facts.receita.find(r=>r.cnpj===selected.cnpj&&(!selectedPeriodKey||periodKey(r.periodo)===selectedPeriodKey)):undefined
 const attainment=finance?.receitaPlanejada?((finance.receitaRealizada??0)/finance.receitaPlanejada):null
 const relatedFcas=selected?fcas.filter(f=>f.depositante_cnpj===selected.cnpj&&(!selectedPeriodKey||f.data_reuniao.slice(0,7)===selectedPeriodKey)).sort((a,b)=>Number(isFcaOverdue(b))-Number(isFcaOverdue(a))||b.data_reuniao.localeCompare(a.data_reuniao)||b.numero-a.numero):[]
 return <section><PageHeader eyebrow="CARTEIRA" title="Depositantes" description="Selecione um cliente para abrir a visão 360º do período, com operação, resultado e FCAs relacionados." actions={<div className="search-box"><span className="material-symbols-rounded">search</span><input aria-label="Buscar depositante" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar depositante…"/></div>}/>
 {selected&&<article className="depositor-360">
   <div className="depositor-hero"><div><span className="panel-eyebrow">DEPOSITANTE SELECIONADO</span><h2>{selected.nome}</h2><p>{selected.codAllStrategy??'Sem código AllStrategy'} · CNPJ {selected.cnpj}</p></div><div className="depositor-owner"><span>Supervisor</span><strong>{supervisor?.nomeExibicao??selected.supervisorId}</strong><small>{selected.moduloId}</small></div><button className="button" onClick={()=>setSelectedCnpj('')}>Fechar visão</button></div>
   <div className="depositor-kpis"><div><span>Produção</span><strong className={`text-${metricStatus(opCurrent?.producaoPct,metaProd)}`}>{pct(opCurrent?.producaoPct)}</strong><small>Meta {pct(metaProd?.metaPct)}</small></div><div><span>Recebimento</span><strong className={`text-${metricStatus(opCurrent?.recebimentoPct,metaRec)}`}>{pct(opCurrent?.recebimentoPct)}</strong><small>Meta {pct(metaRec?.metaPct)}</small></div><div><span>Inventário</span><strong className={`text-${metricStatus(invCurrent?.totalPct,metaInv)}`}>{pct(invCurrent?.totalPct)}</strong><small>Meta {pct(metaInv?.metaPct)}</small></div><div><span>Receita realizada</span><strong>{money(finance?.receitaRealizada)}</strong><small>{attainment==null?'Sem planejamento':`${pct(attainment)} do planejado`}</small></div></div>
   <div className="depositor-grid"><article className="dashboard-panel"><div className="panel-head"><div><span className="panel-eyebrow">HISTÓRICO ATÉ O PERÍODO</span><h2>Evolução operacional</h2></div></div><div className="panel-body"><SimpleLineChart series={historySeries}/></div></article><article className="dashboard-panel"><div className="panel-head"><div><span className="panel-eyebrow">FINANCEIRO</span><h2>Resultado do período</h2></div></div><div className="finance-summary"><div><span>Planejado</span><strong>{money(finance?.receitaPlanejada)}</strong></div><div><span>Realizado</span><strong>{money(finance?.receitaRealizada)}</strong></div><div><span>Atingimento</span><strong className={attainment!=null&&attainment>=1?'text-ok':attainment!=null&&attainment<.95?'text-crit':''}>{pct(attainment)}</strong></div></div></article></div>
   <article className="dashboard-panel depositor-fcas"><div className="panel-head"><div><span className="panel-eyebrow">FCA DO PERÍODO</span><h2>Fatos, causas e ações do cliente</h2></div><span className="panel-chip">{relatedFcas.length} registro(s)</span></div>{fcaLoading?<div className="table-empty">Carregando FCAs…</div>:relatedFcas.length?<div className="fca-mini-list">{relatedFcas.slice(0,8).map(f=>{const display=isFcaOverdue(f)?'VENCIDO':deriveFcaStatus(f);return <Link to={`/fca/${f.id}`} key={f.id}><div><strong>FCA #{String(f.numero).padStart(5,'0')}</strong><span>{new Date(`${f.data_reuniao}T12:00:00`).toLocaleDateString('pt-BR')} · {f.indicador_nome}</span></div><span className={`status-badge status-${display}`}>{display.replace('_',' ')}</span></Link>})}</div>:<div className="table-empty">Nenhum FCA para este depositante no período selecionado.</div>}</article>
 </article>}
 <div className="table-wrap"><table className="depositor-table responsive-data-table"><thead><tr><th scope="col">Depositante</th><th scope="col">Supervisor</th><th scope="col">Módulo</th><th scope="col">Produção</th><th scope="col">Recebimento</th><th scope="col">Inventário</th><th scope="col">CNPJ</th></tr></thead><tbody>{rows.map(d=>{const op=hub.facts.kpiOperacional.find(r=>r.cnpj===d.cnpj&&(!selectedPeriodKey||periodKey(r.periodo)===selectedPeriodKey)),inv=hub.facts.kpiInventarioDepositante.find(r=>r.cnpj===d.cnpj&&(!selectedPeriodKey||periodKey(r.periodo)===selectedPeriodKey)),sup=hub.supervisors.find(s=>s.supervisorId===d.supervisorId);return <tr key={d.cnpj} className={selectedCnpj===d.cnpj?'selected-row':''} onClick={()=>setSelectedCnpj(d.cnpj)}><td data-label="Depositante" data-primary="true"><button type="button" className="table-link depositor-open-button" onClick={event=>{event.stopPropagation();setSelectedCnpj(d.cnpj)}} aria-label={`Abrir visão de ${d.nome}`}><span className="table-primary"><strong>{d.nome}</strong><span>{d.codAllStrategy??'Sem código AllStrategy'}</span></span></button></td><td data-label="Supervisor">{sup?.nomeExibicao??d.supervisorId}</td><td data-label="Módulo"><span className="module-badge">{d.moduloId}</span></td><td data-label="Produção"><span className={`text-${metricStatus(op?.producaoPct,metaProd)}`}>{pct(op?.producaoPct)}</span></td><td data-label="Recebimento"><span className={`text-${metricStatus(op?.recebimentoPct,metaRec)}`}>{pct(op?.recebimentoPct)}</span></td><td data-label="Inventário"><span className={`text-${metricStatus(inv?.totalPct,metaInv)}`}>{pct(inv?.totalPct)}</span></td><td data-label="CNPJ" className="mono">{d.cnpj}</td></tr>})}{!rows.length&&<tr><td colSpan={7} className="table-empty">Nenhum depositante encontrado no escopo.</td></tr>}</tbody></table></div>
 </section>
}
