import { MetricCard } from '../components/MetricCard'
import { PageHeader } from '../components/PageHeader'
import { money, pct, periodKey, revenueRows, sum } from '../lib/dashboard'
import type { DashboardFilters } from '../types/dashboard'
import type { HubBootstrap } from '../types/hub'

export function FinanceiroPage({hub,filters}:{hub:HubBootstrap;filters:DashboardFilters}){
 const rows=revenueRows(hub,filters),planned=sum(rows.map(r=>r.receitaPlanejada)),realized=sum(rows.map(r=>r.receitaRealizada)),balance=realized-planned,attainment=planned?realized/planned:null
 const canShowConsolidatedExpense=hub.profile.perfil==='ADMIN'&&!filters.supervisorId&&!filters.moduloId
 const expenses=canShowConsolidatedExpense?hub.facts.despesa.filter(r=>!filters.periodo||periodKey(r.periodo)===periodKey(filters.periodo)):[]
 const expPlan=sum(expenses.map(r=>r.despesaPlanejada)),expReal=sum(expenses.map(r=>r.despesaRealizada)),result=realized+expReal
 return <section><PageHeader eyebrow="RESULTADO" title="Financeiro" description="Receita planejada versus realizada no escopo selecionado. Despesas são consolidadas porque a base atual não possui dimensão de supervisor ou módulo."/>
 <div className={`kpi-strip finance-kpis ${canShowConsolidatedExpense?'':'finance-kpis-scoped'}`}><MetricCard label="Receita planejada" value={money(planned)} detail={`${rows.length} depositantes`}/><MetricCard label="Receita realizada" value={money(realized)} status={attainment!=null&&attainment>=1?'ok':attainment!=null&&attainment<.9?'crit':'warn'}/><MetricCard label="Atingimento" value={pct(attainment)} meta={money(balance)} status={attainment!=null&&attainment>=1?'ok':attainment!=null&&attainment<.9?'crit':'warn'}/>{canShowConsolidatedExpense&&<><MetricCard label="Despesa realizada" value={money(expReal)} detail={`Planejado ${money(expPlan)}`}/><MetricCard label="Resultado direto" value={money(result)} status={result>=0?'ok':'crit'}/></>}</div>
 {!canShowConsolidatedExpense&&hub.profile.perfil==='ADMIN'&&<div className="scope-note"><span className="material-symbols-rounded">info</span><div><strong>Despesas não aplicadas ao filtro de Supervisor/Módulo</strong><p>A `fDespesa` atual possui período e conta, mas não possui Supervisor ou Módulo. Para evitar um resultado incorreto, os cards de despesa e resultado direto ficam ocultos enquanto esses filtros estiverem ativos.</p></div></div>}
 <article className="dashboard-panel"><div className="panel-head"><div><span className="panel-eyebrow">POR DEPOSITANTE</span><h2>Planejado x realizado</h2></div><span className="panel-chip">{rows.length} depositante(s)</span></div><div className="revenue-list">{rows.map(r=>{const p=r.receitaPlanejada??0,real=r.receitaRealizada??0,at=p?real/p:0;return <div className="revenue-row" key={`${r.periodo}-${r.cnpj}`}><div><strong>{r.nomeDepositante}</strong><span>{r.moduloId}</span></div><div className="revenue-bars"><div><span>Plan.</span><i><b style={{width:'100%'}}/></i><em>{money(p)}</em></div><div><span>Real.</span><i><b style={{width:`${Math.min(100,at*100)}%`}}/></i><em>{money(real)}</em></div></div><strong className={at>=1?'text-ok':at>=.9?'text-warn':'text-crit'}>{p?pct(at):'s/ plano'}</strong></div>})}{!rows.length&&<div className="empty-chart">Sem receita no escopo selecionado.</div>}</div></article>
 {canShowConsolidatedExpense&&expenses.length>0&&<article className="dashboard-panel panel-spaced"><div className="panel-head"><div><span className="panel-eyebrow">DESPESAS CONSOLIDADAS</span><h2>Composição do período</h2></div><span className="panel-chip">sem rateio por supervisor</span></div><div className="table-wrap embedded"><table><thead><tr><th>Conta</th><th>Planejado</th><th>Realizado</th><th>Variação</th></tr></thead><tbody>{expenses.map(r=><tr key={`${r.periodo}-${r.codAllStrategy}`}><td><strong>{r.codAllStrategy}</strong></td><td>{money(r.despesaPlanejada)}</td><td>{money(r.despesaRealizada)}</td><td className={(r.despesaRealizada??0)<(r.despesaPlanejada??0)?'text-crit':'text-ok'}>{money((r.despesaRealizada??0)-(r.despesaPlanejada??0))}</td></tr>)}</tbody></table></div></article>}
 </section>
}
