import { MetricCard } from '../components/MetricCard'
import { PageHeader } from '../components/PageHeader'
import { money, pct, revenueRows, sum } from '../lib/dashboard'
import type { DashboardFilters } from '../types/dashboard'
import type { HubBootstrap } from '../types/hub'

export function FinanceiroPage({hub,filters}:{hub:HubBootstrap;filters:DashboardFilters}){
 const rows=revenueRows(hub,filters), planned=sum(rows.map(r=>r.receitaPlanejada)), realized=sum(rows.map(r=>r.receitaRealizada)), balance=realized-planned, attainment=planned?realized/planned:null
 const expenses=hub.facts.despesa.filter(r=>!filters.periodo||r.periodo===filters.periodo), expPlan=sum(expenses.map(r=>r.despesaPlanejada)),expReal=sum(expenses.map(r=>r.despesaRealizada)), result=realized+expReal
 return <section><PageHeader eyebrow="RESULTADO" title="Financeiro" description="Receita planejada versus realizada e, para administradores, visão consolidada de despesas."/>
 <div className="kpi-strip finance-kpis"><MetricCard label="Receita planejada" value={money(planned)} detail={`${rows.length} depositantes`}/><MetricCard label="Receita realizada" value={money(realized)} status={attainment!=null&&attainment>=1?'ok':attainment!=null&&attainment<.9?'crit':'warn'}/><MetricCard label="Atingimento" value={pct(attainment)} meta={money(balance)} status={attainment!=null&&attainment>=1?'ok':attainment!=null&&attainment<.9?'crit':'warn'}/>{hub.profile.perfil==='ADMIN'&&<><MetricCard label="Despesa realizada" value={money(expReal)} detail={`Planejado ${money(expPlan)}`}/><MetricCard label="Resultado direto" value={money(result)} status={result>=0?'ok':'crit'}/></>}</div>
 <article className="dashboard-panel"><div className="panel-head"><div><span className="panel-eyebrow">POR DEPOSITANTE</span><h2>Planejado x realizado</h2></div></div><div className="revenue-list">{rows.map(r=>{const p=r.receitaPlanejada??0,real=r.receitaRealizada??0,at=p?real/p:0;return <div className="revenue-row" key={`${r.periodo}-${r.cnpj}`}><div><strong>{r.nomeDepositante}</strong><span>{r.moduloId}</span></div><div className="revenue-bars"><div><span>Plan.</span><i><b style={{width:'100%'}}/></i><em>{money(p)}</em></div><div><span>Real.</span><i><b style={{width:`${Math.min(100,at*100)}%`}}/></i><em>{money(real)}</em></div></div><strong className={at>=1?'text-ok':at>=.9?'text-warn':'text-crit'}>{p?pct(at):'s/ plano'}</strong></div>})}{!rows.length&&<div className="empty-chart">Sem receita no período selecionado.</div>}</div></article>
 {hub.profile.perfil==='ADMIN'&&expenses.length>0&&<article className="dashboard-panel panel-spaced"><div className="panel-head"><div><span className="panel-eyebrow">DESPESAS</span><h2>Composição consolidada</h2></div></div><div className="table-wrap embedded"><table><thead><tr><th>Conta</th><th>Planejado</th><th>Realizado</th><th>Variação</th></tr></thead><tbody>{expenses.map(r=><tr key={`${r.periodo}-${r.codAllStrategy}`}><td><strong>{r.codAllStrategy}</strong></td><td>{money(r.despesaPlanejada)}</td><td>{money(r.despesaRealizada)}</td><td>{money((r.despesaRealizada??0)-(r.despesaPlanejada??0))}</td></tr>)}</tbody></table></div></article>}
 </section>
}
