import { FormEvent, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { FcaFormStepper } from '../components/fca/FcaFormStepper'
import { PageHeader } from '../components/PageHeader'
import { ContextNotice } from '../components/ui/ContextNotice'
import type { HubBootstrap } from '../types/hub'
import type { FcaActionStatus, NewFcaAction } from '../types/fca'
import { createFca } from '../lib/fca'

const emptyAction=():NewFcaAction=>({acao:'',responsavel:'',prazo:'',status:'ABERTO'})
const todaySaoPaulo=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date())
const emailKey=(value:string|null|undefined)=>String(value??'').trim().toLowerCase()

export function NewFcaPage({hub}:{hub:HubBootstrap}){
 const navigate=useNavigate(),isAdmin=hub.profile.perfil==='ADMIN'
 const hasTemporaryCoverage=!isAdmin&&hub.supervisors.some(s=>s.supervisorId!==hub.profile.supervisorId)
 const canChooseSupervisor=isAdmin||hasTemporaryCoverage||!hub.profile.supervisorId
 const initialSupervisorId=isAdmin?'':hub.profile.supervisorId??(hub.supervisors.length===1?hub.supervisors[0].supervisorId:'')
 const[dataReuniao,setDataReuniao]=useState(todaySaoPaulo()),[supervisorId,setSupervisorId]=useState(initialSupervisorId),[moduloId,setModuloId]=useState(''),[depositanteCnpj,setDepositanteCnpj]=useState(''),[indicadorCodigo,setIndicadorCodigo]=useState(''),[causa,setCausa]=useState(''),[acoes,setAcoes]=useState<NewFcaAction[]>([emptyAction()]),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null)
 const modules=useMemo(()=>Array.from(new Set(hub.supervisorModules.filter(i=>!supervisorId||i.supervisorId===supervisorId).map(i=>i.moduloId))).sort(),[hub.supervisorModules,supervisorId])
 const depositantes=useMemo(()=>hub.depositantes.filter(i=>(!supervisorId||i.supervisorId===supervisorId)&&(!moduloId||i.moduloId===moduloId)).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR')),[hub.depositantes,supervisorId,moduloId])
 const indicadores=useMemo(()=>hub.indicadores.filter(i=>i.grupo.trim().toUpperCase()==='KPI').sort((a,b)=>a.indicador.localeCompare(b.indicador,'pt-BR')),[hub.indicadores])
 function updateAction(index:number,field:keyof NewFcaAction,value:string){setAcoes(c=>c.map((a,i)=>i===index?{...a,[field]:value}:a))}
 function currentUserSubstitution(targetSupervisorId:string,targetModuloId:string){return hub.substituicoes.find(i=>i.ativo&&i.supervisorTitularId===targetSupervisorId&&i.moduloId===targetModuloId&&((hub.profile.supervisorId&&i.supervisorSubstitutoId===hub.profile.supervisorId)||emailKey(i.supervisorSubstitutoEmail)===emailKey(hub.profile.email)))}
 async function handleSubmit(event:FormEvent){event.preventDefault();setError(null);const dep=depositantes.find(i=>i.cnpj===depositanteCnpj),ind=indicadores.find(i=>i.codigo===indicadorCodigo),sup=hub.supervisors.find(i=>i.supervisorId===dep?.supervisorId);if(!dep||!ind||!sup||!moduloId){setError('Preencha supervisor, módulo, depositante e indicador.');return}if(!causa.trim()){setError('Informe a causa do FCA.');return}const validActions=acoes.filter(a=>a.acao.trim());if(acoes.some(a=>!a.acao.trim()&&(a.responsavel||a.prazo))){setError('Há uma ação incompleta. Informe a descrição ou remova a linha.');return}const substitution=currentUserSubstitution(dep.supervisorId,moduloId);setSaving(true);try{const created=await createFca({dataReuniao,supervisorId:dep.supervisorId,supervisorNome:sup.supervisor,moduloId,depositanteCnpj:dep.cnpj,depositanteNome:dep.nome,indicadorCodigo:ind.codigo,indicadorNome:ind.indicador,causa:causa.trim(),substituicaoId:substitution?.substituicaoId??null,substitutoId:substitution?.supervisorSubstitutoId??null,substitutoNome:substitution?.supervisorSubstituto??null,acoes:validActions});navigate(`/fca/${created.id}`,{state:{justCreated:created.numero}})}catch(err){setError(err instanceof Error?err.message:'Não foi possível salvar o FCA.')}finally{setSaving(false)}}
 return <section className="fca-page fca-editor-page">
  <PageHeader eyebrow="FCA · NOVO REGISTRO" title="Novo FCA" description="Registre o contexto, documente a causa e transforme a análise em um plano de ação rastreável." actions={<Link className="button" to="/fca"><span className="material-symbols-rounded" aria-hidden="true">arrow_back</span>Voltar</Link>}/>
  <FcaFormStepper/>
  {hasTemporaryCoverage&&<ContextNotice icon="event_repeat" title="Acesso por cobertura temporária" description="Você pode selecionar seu próprio escopo ou o supervisor titular que está cobrindo. Apenas módulos e depositantes autorizados ficam disponíveis."/>}
  <form className="fca-form" onSubmit={handleSubmit}>
   <div className="form-section"><div className="form-section-heading"><span className="material-symbols-rounded" aria-hidden="true">badge</span><div><h2>Identificação</h2><p>Defina o contexto operacional do registro.</p></div></div><div className="form-grid form-grid-3"><div><label>Data da reunião</label><input type="date" value={dataReuniao} onChange={e=>setDataReuniao(e.target.value)} required/></div><div><label>Supervisor titular</label><select value={supervisorId} onChange={e=>{setSupervisorId(e.target.value);setModuloId('');setDepositanteCnpj('')}} disabled={!canChooseSupervisor} required><option value="">Selecione</option>{hub.supervisors.map(i=><option key={i.supervisorId} value={i.supervisorId}>{i.nomeExibicao}</option>)}</select></div><div><label>Módulo</label><select value={moduloId} onChange={e=>{setModuloId(e.target.value);setDepositanteCnpj('')}} required><option value="">Selecione</option>{modules.map(i=><option key={i}>{i}</option>)}</select></div><div className="span-2"><label>Depositante</label><select value={depositanteCnpj} onChange={e=>setDepositanteCnpj(e.target.value)} required><option value="">Selecione pelo nome</option>{depositantes.map(i=><option key={i.cnpj} value={i.cnpj}>{i.nome} · {i.cnpj}</option>)}</select></div><div><label>Indicador</label><select value={indicadorCodigo} onChange={e=>setIndicadorCodigo(e.target.value)} required><option value="">Selecione</option>{indicadores.map(i=><option key={i.codigo} value={i.codigo}>{i.indicador}</option>)}</select></div></div></div>
   <div className="form-section"><div className="form-section-heading"><span className="material-symbols-rounded" aria-hidden="true">troubleshoot</span><div><h2>Análise da causa</h2><p>Documente o desvio com contexto suficiente para leitura e auditoria.</p></div></div><label>Causa / desvio identificado</label><textarea value={causa} onChange={e=>setCausa(e.target.value)} rows={6} placeholder="Descreva o problema, o impacto e a causa identificada…" required/></div>
   <div className="form-section"><div className="form-section-heading-row"><div className="form-section-heading"><span className="material-symbols-rounded" aria-hidden="true">task_alt</span><div><h2>Plano de ação</h2><p>Defina ações, responsáveis, prazos e acompanhamento.</p></div></div><button type="button" className="add-action-button" onClick={()=>setAcoes(c=>[...c,emptyAction()])}><span className="material-symbols-rounded" aria-hidden="true">add</span>Nova ação</button></div><div className="actions-stack">{acoes.map((acao,index)=><div className="action-card" key={index}><div className="action-card-title"><span className="action-number">{String(index+1).padStart(2,'0')}</span><strong>Ação</strong><button type="button" className="action-remove" onClick={()=>setAcoes(c=>c.length===1?c:c.filter((_,i)=>i!==index))} disabled={acoes.length===1}><span className="material-symbols-rounded" aria-hidden="true">delete</span>Remover</button></div><div className="form-grid form-grid-action"><div className="span-2"><label>Descrição da ação</label><textarea rows={3} value={acao.acao} onChange={e=>updateAction(index,'acao',e.target.value)}/></div><div><label>Responsável</label><input value={acao.responsavel} onChange={e=>updateAction(index,'responsavel',e.target.value)}/></div><div><label>Prazo</label><input type="date" value={acao.prazo} onChange={e=>updateAction(index,'prazo',e.target.value)}/></div><div><label>Status</label><select value={acao.status} onChange={e=>updateAction(index,'status',e.target.value as FcaActionStatus)}><option value="ABERTO">Aberto</option><option value="EM_ANDAMENTO">Em andamento</option><option value="CONCLUIDO">Concluído</option><option value="CANCELADO">Cancelado</option></select></div></div></div>)}</div></div>
   {error&&<div className="notice notice-error" role="alert">{error}</div>}<div className="form-actions sticky-form-actions"><Link className="button" to="/fca">Cancelar</Link><button className="button button-primary" type="submit" disabled={saving}>{saving?'Salvando…':'Salvar FCA'}</button></div>
  </form>
 </section>
}
