import { PageHeader } from '../components/PageHeader'
import { avg, indicatorMeta, metricStatus, pct } from '../lib/dashboard'
import type { DashboardFilters, MetricStatus } from '../types/dashboard'
import type { HubBootstrap } from '../types/hub'

const rank:Record<MetricStatus,number>={crit:3,warn:2,neutral:1,ok:0}
const label:Record<MetricStatus,string>={ok:'Dentro da meta',warn:'Atenção',crit:'Crítico',neutral:'Sem referência'}

export function SupervisorsPage({hub,filters,onFiltersChange}:{hub:HubBootstrap;filters:DashboardFilters;onFiltersChange:(next:DashboardFilters)=>void}){
 const metaProd=indicatorMeta(hub,'Lead Time Produção'),metaRec=indicatorMeta(hub,'Lead Time Recebimento'),metaInv=indicatorMeta(hub,'Inventário')
 const cards=hub.supervisors.map(s=>{const op=hub.facts.kpiOperacional.filter(r=>(!filters.periodo||r.periodo===filters.periodo)&&r.supervisorId===s.supervisorId&&(!filters.moduloId||r.moduloId===filters.moduloId));const inv=hub.facts.kpiInventarioDepositante.filter(r=>(!filters.periodo||r.periodo===filters.periodo)&&r.supervisorId===s.supervisorId&&(!filters.moduloId||r.moduloId===filters.moduloId));const deps=hub.depositantes.filter(d=>d.supervisorId===s.supervisorId&&(!filters.moduloId||d.moduloId===filters.moduloId));const prod=avg(op.map(x=>x.producaoPct)),rec=avg(op.map(x=>x.recebimentoPct)),invAvg=avg(inv.map(x=>x.totalPct));const statuses=[metricStatus(prod,metaProd),metricStatus(rec,metaRec),metricStatus(invAvg,metaInv)];const status=statuses.reduce((a,b)=>rank[b]>rank[a]?b:a,'ok' as MetricStatus);return {s,prod,rec,inv:invAvg,deps,status}}).sort((a,b)=>rank[b.status]-rank[a.status]||a.s.nomeExibicao.localeCompare(b.s.nomeExibicao,'pt-BR'))
 const selected=filters.supervisorId?cards.find(c=>c.s.supervisorId===filters.supervisorId):null
 const detailRows=selected?.deps.map(d=>{const op=hub.facts.kpiOperacional.find(r=>(!filters.periodo||r.periodo===filters.periodo)&&r.cnpj===d.cnpj);const inv=hub.facts.kpiInventarioDepositante.find(r=>(!filters.periodo||r.periodo===filters.periodo)&&r.cnpj===d.cnpj);const statuses=[metricStatus(op?.producaoPct,metaProd),metricStatus(op?.recebimentoPct,metaRec),metricStatus(inv?.totalPct,metaInv)];const status=statuses.reduce((a,b)=>rank[b]>rank[a]?b:a,'ok' as MetricStatus);return {d,op,inv,status}}).sort((a,b)=>rank[b.status]-rank[a.status]||a.d.nome.localeCompare(b.d.nome,'pt-BR'))??[]
 return <section><PageHeader eyebrow="LIDERANÇA OPERACIONAL" title="Supervisores" description="Visão comparativa por responsável, módulo e carteira de depositantes."/>
 <div className="supervisor-grid">{cards.map(({s,prod,rec,inv,deps,status})=><button className={`supervisor-card supervisor-card-${status} ${filters.supervisorId===s.supervisorId?'selected':''}`} key={s.supervisorId} onClick={()=>onFiltersChange({...filters,supervisorId:filters.supervisorId===s.supervisorId?'':s.supervisorId,moduloId:''})}><div className="supervisor-head">{s.fotoUrl?<img src={s.fotoUrl} alt=""/>:<span className="supervisor-avatar">{s.nomeExibicao.slice(0,2).toUpperCase()}</span>}<div><strong>{s.nomeExibicao}</strong><span>{deps.length} depositante(s)</span></div><span className={`supervisor-health supervisor-health-${status}`}>{label[status]}</span></div><div className="supervisor-metrics"><div><span>Produção</span><b className={`text-${metricStatus(prod,metaProd)}`}>{pct(prod)}</b></div><div><span>Recebimento</span><b className={`text-${metricStatus(rec,metaRec)}`}>{pct(rec)}</b></div><div><span>Inventário</span><b className={`text-${metricStatus(inv,metaInv)}`}>{pct(inv)}</b></div></div><div className="supervisor-modules">{Array.from(new Set(deps.map(d=>d.moduloId))).map(m=><span key={m}>{m}</span>)}</div></button>)}</div>
 {selected&&<article className="dashboard-panel panel-spaced supervisor-portfolio"><div className="panel-head"><div><span className="panel-eyebrow">CARTEIRA SELECIONADA</span><h2>{selected.s.nomeExibicao} · {selected.deps.length} depositante(s)</h2></div><button className="button" onClick={()=>onFiltersChange({...filters,supervisorId:'',moduloId:''})}>Limpar seleção</button></div><div className="table-wrap embedded"><table className="status-table"><thead><tr><th>Depositante</th><th>Módulo</th><th>Produção</th><th>Recebimento</th><th>Inventário</th><th>Status</th></tr></thead><tbody>{detailRows.map(({d,op,inv,status})=><tr key={d.cnpj}><td><strong>{d.nome}</strong></td><td>{d.moduloId}</td><td><span className={`metric-cell metric-cell-${metricStatus(op?.producaoPct,metaProd)}`}>{pct(op?.producaoPct)}</span></td><td><span className={`metric-cell metric-cell-${metricStatus(op?.recebimentoPct,metaRec)}`}>{pct(op?.recebimentoPct)}</span></td><td><span className={`metric-cell metric-cell-${metricStatus(inv?.totalPct,metaInv)}`}>{pct(inv?.totalPct)}</span></td><td><span className={`row-status row-status-${status}`}>{label[status]}</span></td></tr>)}</tbody></table></div></article>}
 </section>
}
