import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { avg, indicatorMeta, metricStatus, pct } from '../lib/dashboard'
import type { DashboardFilters, MetricStatus } from '../types/dashboard'
import type { HubBootstrap } from '../types/hub'

const rank:Record<MetricStatus,number>={crit:3,warn:2,neutral:1,ok:0}
const label:Record<MetricStatus,string>={ok:'Dentro da meta',warn:'Atenção',crit:'Crítico',neutral:'Sem dados no período'}

export function SupervisorsPage({hub,filters}:{hub:HubBootstrap;filters:DashboardFilters}){
 const navigate=useNavigate()
 const[selectedSupervisorId,setSelectedSupervisorId]=useState(filters.supervisorId)
 useEffect(()=>setSelectedSupervisorId(filters.supervisorId),[filters.supervisorId])
 const metaProd=indicatorMeta(hub,'Lead Time Produção'),metaRec=indicatorMeta(hub,'Lead Time Recebimento'),metaInv=indicatorMeta(hub,'Inventário')
 const cards=hub.supervisors.map(s=>{const op=hub.facts.kpiOperacional.filter(r=>(!filters.periodo||r.periodo===filters.periodo)&&r.supervisorId===s.supervisorId&&(!filters.moduloId||r.moduloId===filters.moduloId));const inv=hub.facts.kpiInventarioDepositante.filter(r=>(!filters.periodo||r.periodo===filters.periodo)&&r.supervisorId===s.supervisorId&&(!filters.moduloId||r.moduloId===filters.moduloId));const deps=hub.depositantes.filter(d=>d.supervisorId===s.supervisorId&&(!filters.moduloId||d.moduloId===filters.moduloId));const prod=avg(op.map(x=>x.producaoPct)),rec=avg(op.map(x=>x.recebimentoPct)),invAvg=avg(inv.map(x=>x.totalPct));const statuses=[metricStatus(prod,metaProd),metricStatus(rec,metaRec),metricStatus(invAvg,metaInv)];const status=statuses.reduce((a,b)=>rank[b]>rank[a]?b:a,'ok' as MetricStatus);const depStatuses=deps.map(d=>{const o=op.find(r=>r.cnpj===d.cnpj),i=inv.find(r=>r.cnpj===d.cnpj);const ss=[metricStatus(o?.producaoPct,metaProd),metricStatus(o?.recebimentoPct,metaRec),metricStatus(i?.totalPct,metaInv)];return ss.reduce((a,b)=>rank[b]>rank[a]?b:a,'ok' as MetricStatus)});const critCount=depStatuses.filter(x=>x==='crit').length;const warnCount=depStatuses.filter(x=>x==='warn').length;return {s,prod,rec,inv:invAvg,deps,status,critCount,warnCount}}).sort((a,b)=>b.critCount-a.critCount||b.warnCount-a.warnCount||rank[b.status]-rank[a.status]||a.s.nomeExibicao.localeCompare(b.s.nomeExibicao,'pt-BR'))
 const visibleCards=filters.supervisorId?cards.filter(c=>c.s.supervisorId===filters.supervisorId):cards
 const selected=selectedSupervisorId?cards.find(c=>c.s.supervisorId===selectedSupervisorId):null
 const detailRows=selected?.deps.map(d=>{const op=hub.facts.kpiOperacional.find(r=>(!filters.periodo||r.periodo===filters.periodo)&&r.cnpj===d.cnpj);const inv=hub.facts.kpiInventarioDepositante.find(r=>(!filters.periodo||r.periodo===filters.periodo)&&r.cnpj===d.cnpj);const statuses=[metricStatus(op?.producaoPct,metaProd),metricStatus(op?.recebimentoPct,metaRec),metricStatus(inv?.totalPct,metaInv)];const status=statuses.reduce((a,b)=>rank[b]>rank[a]?b:a,'ok' as MetricStatus);return {d,op,inv,status}}).sort((a,b)=>rank[b.status]-rank[a.status]||a.d.nome.localeCompare(b.d.nome,'pt-BR'))??[]
 const cardBadge=(critCount:number,warnCount:number,status:MetricStatus)=>critCount?`${critCount} crítico${critCount>1?'s':''}`:warnCount?`${warnCount} em atenção`:label[status]
 function openDepositante(cnpj:string){sessionStorage.setItem('bi-logistico-v2:depositante',cnpj);navigate('/depositantes')}
 return <section><PageHeader eyebrow="LIDERANÇA OPERACIONAL" title="Supervisores" description="Compare as carteiras e selecione um responsável para abrir o detalhamento dos depositantes."/>
 <div className="supervisor-grid">{visibleCards.map(({s,prod,rec,inv,deps,status,critCount,warnCount})=><button className={`supervisor-card supervisor-card-${status} ${selectedSupervisorId===s.supervisorId?'selected':''}`} key={s.supervisorId} onClick={()=>setSelectedSupervisorId(selectedSupervisorId===s.supervisorId?'':s.supervisorId)}><div className="supervisor-head">{s.fotoUrl?<img src={s.fotoUrl} alt=""/>:<span className="supervisor-avatar">{s.nomeExibicao.slice(0,2).toUpperCase()}</span>}<div><strong>{s.nomeExibicao}</strong><span>{deps.length} depositante(s)</span></div><span className={`supervisor-health supervisor-health-${status}`}>{cardBadge(critCount,warnCount,status)}</span></div><div className="supervisor-metrics"><div><span>Produção</span><b className={`text-${metricStatus(prod,metaProd)}`}>{pct(prod)}</b></div><div><span>Recebimento</span><b className={`text-${metricStatus(rec,metaRec)}`}>{pct(rec)}</b></div><div><span>Inventário</span><b className={`text-${metricStatus(inv,metaInv)}`}>{pct(inv)}</b></div></div><div className="supervisor-modules">{Array.from(new Set(deps.map(d=>d.moduloId))).map(m=><span key={m}>{m}</span>)}</div></button>)}</div>
 {selected&&<article className="dashboard-panel panel-spaced supervisor-portfolio"><div className="panel-head"><div><span className="panel-eyebrow">CARTEIRA SELECIONADA</span><h2>{selected.s.nomeExibicao} · {selected.deps.length} depositante(s)</h2></div><button className="button" onClick={()=>setSelectedSupervisorId('')}>Fechar carteira</button></div><div className="table-wrap embedded"><table className="status-table"><thead><tr><th>Depositante</th><th>Módulo</th><th>Produção</th><th>Recebimento</th><th>Inventário</th><th>Status</th></tr></thead><tbody>{detailRows.map(({d,op,inv,status})=><tr key={d.cnpj}><td><button className="table-link" onClick={()=>openDepositante(d.cnpj)}><strong>{d.nome}</strong></button></td><td>{d.moduloId}</td><td><span className={`metric-cell metric-cell-${metricStatus(op?.producaoPct,metaProd)}`}>{pct(op?.producaoPct)}</span></td><td><span className={`metric-cell metric-cell-${metricStatus(op?.recebimentoPct,metaRec)}`}>{pct(op?.recebimentoPct)}</span></td><td><span className={`metric-cell metric-cell-${metricStatus(inv?.totalPct,metaInv)}`}>{pct(inv?.totalPct)}</span></td><td><span className={`row-status row-status-${status}`}>{label[status]}</span></td></tr>)}</tbody></table></div></article>}
 </section>
}
