import { useMemo, useState, type FormEvent } from 'react'
import { coverageToForm, saveCoverage, saveSubstitute } from '../lib/substitutions'
import type { HubBootstrap, HubSubstituicao, HubSubstituto } from '../types/hub'

const datePt=(value:string)=>value?new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR'):'—'
type CoverageStatus='ATIVA'|'ENCERRADA'|'CANCELADA'
type CoverageForm={id:string;titularId:string;substitutoMasterId:string;moduloId:string;dataInicio:string;dataFim:string;motivo:string;status:CoverageStatus}
const emptySub={id:'',codigo:'',nome:'',email:'',ativo:true}
const emptyCoverage:CoverageForm={id:'',titularId:'',substitutoMasterId:'',moduloId:'',dataInicio:'',dataFim:'',motivo:'',status:'ATIVA'}

export function SubstitutionManager({hub,onRefresh}:{hub:HubBootstrap;onRefresh:()=>Promise<void>}){
 const isAdmin=hub.profile.perfil==='ADMIN'
 const [subForm,setSubForm]=useState(emptySub)
 const [covForm,setCovForm]=useState<CoverageForm>(emptyCoverage)
 const [saving,setSaving]=useState(false)
 const [message,setMessage]=useState<string|null>(null)
 const coverage=useMemo(()=>[...hub.substituicoes].sort((a,b)=>Number(b.ativo)-Number(a.ativo)||b.dataInicio.localeCompare(a.dataInicio)),[hub.substituicoes])
 const modulesForTitular=Array.from(new Set(hub.supervisorModules.filter(m=>m.supervisorId===covForm.titularId&&m.ativo).map(m=>m.moduloId))).sort()

 function editSubstitute(s:HubSubstituto){setSubForm({id:s.id,codigo:s.codigo,nome:s.nome,email:s.email??'',ativo:s.ativo});setMessage(null)}
 function editCoverage(c:HubSubstituicao){const f=coverageToForm(c);setCovForm({...f,status:f.status as CoverageStatus});setMessage(null)}
 async function submitSub(e:FormEvent){e.preventDefault();setSaving(true);setMessage(null);try{await saveSubstitute(subForm);setSubForm(emptySub);await onRefresh();setMessage('Substituto salvo.')}catch(err){setMessage(err instanceof Error?err.message:'Falha ao salvar substituto.')}finally{setSaving(false)}}
 async function submitCoverage(e:FormEvent){e.preventDefault();const titular=hub.supervisors.find(s=>s.supervisorId===covForm.titularId),sub=hub.substitutos.find(s=>s.id===covForm.substitutoMasterId);if(!titular||!sub){setMessage('Selecione titular e substituto.');return}setSaving(true);setMessage(null);try{await saveCoverage({id:covForm.id||undefined,titularId:titular.supervisorId,titularNome:titular.nomeExibicao,substituto:sub,moduloId:covForm.moduloId,dataInicio:covForm.dataInicio,dataFim:covForm.dataFim,motivo:covForm.motivo,status:covForm.status});setCovForm(emptyCoverage);await onRefresh();setMessage('Cobertura salva.')}catch(err){setMessage(err instanceof Error?err.message:'Falha ao salvar cobertura.')}finally{setSaving(false)}}

 return <article className="dashboard-panel panel-spaced"><div className="panel-head"><div><span className="panel-eyebrow">COBERTURA DE SUPERVISÃO</span><h2>Substituições e períodos de cobertura</h2></div><span className="panel-chip">{coverage.filter(c=>c.ativo).length} ativa(s)</span></div>
  {coverage.length?<div className="coverage-list">{coverage.map(c=>{const titular=hub.supervisors.find(s=>s.supervisorId===c.supervisorTitularId);return <div className="coverage-row" key={c.substituicaoId}><div className="coverage-flow"><div><small>Titular</small><strong>{titular?.nomeExibicao??c.supervisorTitularId}</strong></div><span className="material-symbols-rounded">arrow_forward</span><div><small>Substituto</small><strong>{c.supervisorSubstituto}</strong><span>{c.supervisorSubstitutoEmail??'Sem e-mail de acesso'}</span></div></div><div><small>Módulo</small><strong>{c.moduloId}</strong></div><div><small>Período</small><strong>{datePt(c.dataInicio)} – {datePt(c.dataFim)}</strong></div><div><small>Motivo</small><strong>{c.motivo??'Não informado'}</strong></div><span className={`coverage-status ${c.ativo?'active':'closed'}`}>{c.ativo?'Em vigor':c.status==='CANCELADA'?'Cancelada':'Encerrada'}</span>{isAdmin&&c.origem==='SUPABASE'&&<button className="icon-button" title="Editar cobertura" onClick={()=>editCoverage(c)}><span className="material-symbols-rounded">edit</span></button>}</div>})}</div>:<div className="table-empty">Nenhuma cobertura cadastrada.</div>}
  {isAdmin&&<div className="substitution-admin"><div className="substitution-admin-head"><div><span className="panel-eyebrow">ADMINISTRAÇÃO</span><h3>Cadastro e edição</h3></div>{message&&<span className="form-feedback">{message}</span>}</div><div className="substitution-admin-grid">
   <form className="substitution-form" onSubmit={submitSub}><div className="form-title"><strong>{subForm.id?'Editar substituto':'Novo substituto'}</strong><span>Pessoa que poderá assumir uma cobertura temporária.</span></div><label>ID / matrícula<input required value={subForm.codigo} onChange={e=>setSubForm({...subForm,codigo:e.target.value})}/></label><label>Nome<input required value={subForm.nome} onChange={e=>setSubForm({...subForm,nome:e.target.value})}/></label><label>E-mail de acesso<input type="email" value={subForm.email} onChange={e=>setSubForm({...subForm,email:e.target.value})} placeholder="nome@empresa.com.br"/></label><label className="check-label"><input type="checkbox" checked={subForm.ativo} onChange={e=>setSubForm({...subForm,ativo:e.target.checked})}/>Cadastro ativo</label><div className="form-actions"><button type="button" className="button" onClick={()=>setSubForm(emptySub)}>Limpar</button><button disabled={saving} className="button button-primary">Salvar substituto</button></div><div className="substitute-chips">{hub.substitutos.map(s=><button type="button" key={s.id} onClick={()=>editSubstitute(s)}>{s.nome}{s.email?' · acesso':''}</button>)}</div></form>
   <form className="substitution-form" onSubmit={submitCoverage}><div className="form-title"><strong>{covForm.id?'Editar cobertura':'Nova cobertura'}</strong><span>Define escopo, período e substituto responsável.</span></div><label>Supervisor titular<select required value={covForm.titularId} onChange={e=>setCovForm({...covForm,titularId:e.target.value,moduloId:''})}><option value="">Selecione</option>{hub.supervisors.map(s=><option key={s.supervisorId} value={s.supervisorId}>{s.nomeExibicao}</option>)}</select></label><label>Substituto<select required value={covForm.substitutoMasterId} onChange={e=>setCovForm({...covForm,substitutoMasterId:e.target.value})}><option value="">Selecione</option>{hub.substitutos.filter(s=>s.ativo||s.id===covForm.substitutoMasterId).map(s=><option key={s.id} value={s.id}>{s.nome}{s.email?` · ${s.email}`:' · sem e-mail'}</option>)}</select></label><label>Módulo<select required value={covForm.moduloId} onChange={e=>setCovForm({...covForm,moduloId:e.target.value})}><option value="">Selecione</option>{modulesForTitular.map(m=><option key={m}>{m}</option>)}</select></label><div className="date-pair"><label>Início<input required type="date" value={covForm.dataInicio} onChange={e=>setCovForm({...covForm,dataInicio:e.target.value})}/></label><label>Fim<input required type="date" min={covForm.dataInicio||undefined} value={covForm.dataFim} onChange={e=>setCovForm({...covForm,dataFim:e.target.value})}/></label></div><label>Motivo<input value={covForm.motivo} onChange={e=>setCovForm({...covForm,motivo:e.target.value})} placeholder="Férias, afastamento…"/></label><label>Status<select value={covForm.status} onChange={e=>setCovForm({...covForm,status:e.target.value as CoverageStatus})}><option value="ATIVA">Ativa</option><option value="ENCERRADA">Encerrada</option><option value="CANCELADA">Cancelada</option></select></label><div className="form-actions"><button type="button" className="button" onClick={()=>setCovForm(emptyCoverage)}>Limpar</button><button disabled={saving} className="button button-primary">Salvar cobertura</button></div></form>
  </div></div>}
 </article>
}
