create table if not exists public.app_governance (
  user_id uuid primary key references public.profiles(id) on delete restrict,
  governance_role text not null check (governance_role in ('OWNER','ADMIN')),
  created_at timestamptz not null default now(),
  created_by uuid null,
  updated_at timestamptz not null default now()
);

create unique index if not exists app_governance_single_owner_idx
  on public.app_governance ((governance_role))
  where governance_role = 'OWNER';

create table if not exists public.access_governance_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid null,
  actor_email text null,
  target_id uuid not null,
  action text not null,
  previous_role text null,
  new_role text null,
  created_at timestamptz not null default now()
);

alter table public.app_governance enable row level security;
alter table public.access_governance_audit enable row level security;

revoke all on table public.app_governance from anon, authenticated;
revoke all on table public.access_governance_audit from anon, authenticated;
grant select on table public.app_governance to authenticated;
grant select on table public.access_governance_audit to authenticated;

create or replace function public.is_bi_owner()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.app_governance g
    join public.profiles p on p.id = g.user_id
    where g.user_id = (select auth.uid())
      and g.governance_role = 'OWNER'
      and p.ativo = true
  );
$$;

create or replace function public.is_bi_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.app_governance g
    join public.profiles p on p.id = g.user_id
    where g.user_id = (select auth.uid())
      and g.governance_role in ('OWNER','ADMIN')
      and p.ativo = true
  );
$$;

revoke all on function public.is_bi_owner() from public, anon;
revoke all on function public.is_bi_admin() from public, anon;
grant execute on function public.is_bi_owner() to authenticated;
grant execute on function public.is_bi_admin() to authenticated;

drop policy if exists app_governance_select_self_or_owner on public.app_governance;
create policy app_governance_select_self_or_owner
  on public.app_governance for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_bi_owner()));

drop policy if exists access_governance_audit_owner_select on public.access_governance_audit;
create policy access_governance_audit_owner_select
  on public.access_governance_audit for select to authenticated
  using ((select public.is_bi_owner()));

create or replace function public.list_bi_access_users()
returns table (
  user_id uuid,
  email text,
  nome text,
  ativo boolean,
  perfil_operacional text,
  governance_role text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    p.id,
    p.email,
    p.nome,
    p.ativo,
    p.perfil,
    coalesce(g.governance_role, 'USER')
  from public.profiles p
  left join public.app_governance g on g.user_id = p.id
  where (select public.is_bi_owner())
  order by case coalesce(g.governance_role,'USER') when 'OWNER' then 0 when 'ADMIN' then 1 else 2 end, p.nome;
$$;

revoke all on function public.list_bi_access_users() from public, anon;
grant execute on function public.list_bi_access_users() to authenticated;

create or replace function public.set_bi_admin_role(p_target_id uuid, p_make_admin boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_email text;
  v_previous_role text;
  v_target_exists boolean;
begin
  if not (select public.is_bi_owner()) then
    raise exception 'OWNER_REQUIRED';
  end if;

  select email into v_actor_email from public.profiles where id = (select auth.uid());
  select exists(select 1 from public.profiles where id = p_target_id) into v_target_exists;
  if not v_target_exists then
    raise exception 'TARGET_NOT_FOUND';
  end if;

  select governance_role into v_previous_role
  from public.app_governance
  where user_id = p_target_id;

  if v_previous_role = 'OWNER' then
    raise exception 'OWNER_IMMUTABLE';
  end if;

  if p_make_admin then
    insert into public.app_governance(user_id, governance_role, created_by, updated_at)
    values (p_target_id, 'ADMIN', (select auth.uid()), now())
    on conflict (user_id) do update
      set governance_role = 'ADMIN', updated_at = now();
  else
    delete from public.app_governance
    where user_id = p_target_id and governance_role = 'ADMIN';
  end if;

  insert into public.access_governance_audit(
    actor_id, actor_email, target_id, action, previous_role, new_role
  ) values (
    (select auth.uid()),
    v_actor_email,
    p_target_id,
    case when p_make_admin then 'GRANT_ADMIN' else 'REVOKE_ADMIN' end,
    coalesce(v_previous_role,'USER'),
    case when p_make_admin then 'ADMIN' else 'USER' end
  );
end;
$$;

revoke all on function public.set_bi_admin_role(uuid, boolean) from public, anon;
grant execute on function public.set_bi_admin_role(uuid, boolean) to authenticated;

-- O registro inicial de OWNER é dado de bootstrap do ambiente e não deve
-- depender de nome/e-mail hardcoded na migration. Em produção, ele é
-- provisionado uma única vez por operação administrativa segura.
